# Generated by Django 4.1.7 on 2023-02-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calories_counter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="Category",
            new_name="category",
        ),
    ]
