# Generated by Django 4.1.7 on 2023-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calories_counter", "0004_alter_recipe_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(upload_to="recipes/covers/%Y/%m/%d"),
        ),
    ]
